name: pyaos-lesson
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.9
  - s3fs==0.4.2
  - xarray==0.19.0
  - metpy==1.1.0
  - pandas==1.2.5
  - numpy==1.21.2
  - netcdf==1.5.7
  - zarr==2.8.3
  - nc-time-axis==1.3.1
  - jupyterlab==3.1.7
  - cartopy==0.20.0
  - fsspec==2021.7.0
  - gcsfs==2021.7.0
